/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


package br.com.kerubin.api.cadastros.fornecedor.entity.produto;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import br.com.kerubin.api.servicecore.mapper.ObjectMapper;

@Component
public class ProdutoDTOConverter {

	@Inject
	private ObjectMapper mapper;

	public Produto convertEntityToDto(ProdutoEntity entity) {
		Produto dto = null;
		if (entity != null) {
			dto = mapper.map(entity, Produto.class, true); // Do not permit passwords fields go outside.
		}
		return dto;
	}


	public ProdutoEntity convertDtoToEntity(Produto dto) {
		ProdutoEntity entity = null;
		if (dto != null) {
			entity = mapper.map(dto, ProdutoEntity.class);
		}
		return entity;
	}


}