/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.entity.produto;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class ProdutoAutoCompleteImpl implements ProdutoAutoComplete {

	private java.util.UUID id;
	
	private String nome;
	
	public ProdutoAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
