/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.entity.produto;

import java.util.stream.Collectors;

import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.DeleteMapping;

import br.com.kerubin.api.cadastros.fornecedor.common.PageResult;

		
import br.com.kerubin.api.cadastros.fornecedor.entity.foto.FotoAutoComplete;

import java.util.Collection;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.RequestParam;

@RestController
@RequestMapping("cadastros/fornecedor/entities/produto")
public class ProdutoController {
	
	@Autowired
	private ProdutoService produtoService;
	
	@Autowired
	ProdutoDTOConverter produtoDTOConverter;
	
	@Transactional
	@PostMapping
	public ResponseEntity<Produto> create(@Valid @RequestBody Produto produto) {
		ProdutoEntity produtoEntity = produtoService.create(produtoDTOConverter.convertDtoToEntity(produto));
		return ResponseEntity.status(HttpStatus.CREATED).body(produtoDTOConverter.convertEntityToDto(produtoEntity));
	}
	
	@Transactional(readOnly = true)
	@GetMapping("/{id}")
	public ResponseEntity<Produto> read(@PathVariable java.util.UUID id) {
		try {
			ProdutoEntity produtoEntity = produtoService.read(id);
			return ResponseEntity.ok(produtoDTOConverter.convertEntityToDto(produtoEntity));
		}
		catch(IllegalArgumentException e) {
			return ResponseEntity.notFound().build();
		}
	}
	
	@Transactional
	@PutMapping("/{id}")
	public ResponseEntity<Produto> update(@PathVariable java.util.UUID id, @Valid @RequestBody Produto produto) {
		try {
			ProdutoEntity produtoEntity = produtoService.update(id, produtoDTOConverter.convertDtoToEntity(produto));
			return ResponseEntity.ok(produtoDTOConverter.convertEntityToDto(produtoEntity));
		}
		catch(IllegalArgumentException e) {
			return ResponseEntity.notFound().build();
		}
	}
	
	@ResponseStatus(HttpStatus.NO_CONTENT)
	@DeleteMapping("/{id}")
	public void delete(@PathVariable java.util.UUID id) {
		produtoService.delete(id);
	}
	
	@ResponseStatus(HttpStatus.NO_CONTENT)
	@PostMapping("/deleteInBulk")
	public void deleteInBulk(@RequestBody java.util.List<java.util.UUID> idList) {
		produtoService.deleteInBulk(idList);
	}
	
	@Transactional(readOnly = true)
	@GetMapping
	public PageResult<Produto> list(ProdutoListFilter produtoListFilter, Pageable pageable) {
		Page<ProdutoEntity> page = produtoService.list(produtoListFilter, pageable);
		List<Produto> content = page.getContent().stream().map(pe -> produtoDTOConverter.convertEntityToDto(pe)).collect(Collectors.toList());
		PageResult<Produto> pageResult = new PageResult<>(content, page.getNumber(), page.getSize(), page.getTotalElements());
		return pageResult;
	}
	
	@Transactional(readOnly = true)
	@GetMapping("/autoComplete")
	public Collection<ProdutoAutoComplete> autoComplete(@RequestParam("query") String query) {
		Collection<ProdutoAutoComplete> result = produtoService.autoComplete(query);
		return result;
	}
	
	
	
	// Begin relationships autoComplete 
	
	@Transactional(readOnly = true)
	@GetMapping("/fotoFotosAutoComplete")
	public Collection<FotoAutoComplete> fotoFotosAutoComplete(@RequestParam("query") String query) {
		Collection<FotoAutoComplete> result = produtoService.fotoFotosAutoComplete(query);
		return result;
	}
	
	// End relationships autoComplete
	
}
