/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.entity.fotoimage;

import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoAutoComplete;

public interface FotoImageService {
	
	public FotoImageEntity create(FotoImageEntity fotoImageEntity);
	
	public FotoImageEntity read(java.util.UUID id);
	
	public FotoImageEntity update(java.util.UUID id, FotoImageEntity fotoImageEntity);
	
	public void delete(java.util.UUID id);
	
	public void deleteInBulk(java.util.List<java.util.UUID> idList);
	
	public Page<FotoImageEntity> list(FotoImageListFilter fotoImageListFilter, Pageable pageable);
	
	public Collection<FotoImageAutoComplete> autoComplete(String query);
	
	// Begin relationships autoComplete 
	public Collection<ProdutoAutoComplete> produtoProdutoAutoComplete(String query);
	// End relationships autoComplete
	 
}
