/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.entity.fotoimage;

import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoEntity;
import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoLookupResult;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import javax.inject.Inject;
import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoRepository;
import org.springframework.boot.test.mock.mockito.MockBean;
import br.com.kerubin.api.messaging.core.DomainEntityEventsPublisher;
import br.com.kerubin.api.cadastros.fornecedor.entity.foto.FotoEntity;
import br.com.kerubin.api.cadastros.fornecedor.entity.foto.FotoLookupResult;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;
import static org.mockito.ArgumentMatchers.any;
import java.util.List;
import java.util.ArrayList;
import java.util.stream.Collectors;
import java.util.Collection;
import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoAutoComplete;

import org.junit.Test;
import static org.assertj.core.api.Assertions.assertThat;
import br.com.kerubin.api.cadastros.fornecedor.CadastrosFornecedorBaseEntityTest;


@RunWith(SpringRunner.class)
public class FotoImageServiceTest extends CadastrosFornecedorBaseEntityTest {
	
	private static final String[] IGNORED_FIELDS = { "id" };
	
	@TestConfiguration
	static class FotoImageServiceTestConfig {
		
		@Bean
		public FotoImageListFilterPredicate fotoImageListFilterPredicate() {
			return new FotoImageListFilterPredicateImpl();
		}
		
		@Bean
		public FotoImageService fotoImageService() {
			return new FotoImageServiceImpl();
		}
		
		@Bean
		public FotoImageDTOConverter fotoImageDTOConverter() {
			return new FotoImageDTOConverter();
		}
		
	}
	
	
	@Inject
	protected FotoImageService fotoImageService;
	
	@Inject
	protected FotoImageDTOConverter fotoImageDTOConverter;
	
	@Inject
	protected FotoImageRepository fotoImageRepository;
	
	@Inject
	protected ProdutoRepository produtoRepository;
	
	@MockBean
	protected DomainEntityEventsPublisher publisher;
	
	// BEGIN CREATE TESTS
	
	@Test
	public void testCreateWithAllFields() throws Exception {
		FotoImage fotoImage = new FotoImage();
		
		fotoImage.setId(java.util.UUID.randomUUID());
		fotoImage.setImagem("Unit tests".getBytes());
		fotoImage.setMiniatura("Unit tests".getBytes());
		fotoImage.setNome(generateRandomString(255));
		fotoImage.setDescricao(generateRandomString(255));
		fotoImage.setTamanho(-2689007458359622824L);
		fotoImage.setTipo(generateRandomString(255));
		
		ProdutoEntity produtoEntityParam = newProdutoEntity();
		ProdutoLookupResult produto = newProdutoLookupResult(produtoEntityParam);
		fotoImage.setProduto(produto);
		
		FotoImageEntity fotoImageEntity = fotoImageService.create(fotoImageDTOConverter.convertDtoToEntity(fotoImage));
		em.flush();
		verify(publisher, times(0)).publish(any());
		FotoImage actual = fotoImageDTOConverter.convertEntityToDto(fotoImageEntity);
		
		
		assertThat(actual).isNotNull();
		assertThat(actual.getId()).isNotNull();
		assertThat(actual).isEqualToIgnoringGivenFields(fotoImage, IGNORED_FIELDS);
		
		
		assertThat(actual.getProduto().getId()).isNotNull();
		assertThat(actual.getProduto()).isEqualToIgnoringGivenFields(fotoImage.getProduto(), IGNORED_FIELDS);
		
	}
	
	@Test
	public void testCreateWithOnlyRecairedFields() throws Exception {
		FotoImage fotoImage = new FotoImage();
		
		fotoImage.setId(java.util.UUID.randomUUID());
		FotoImageEntity fotoImageEntity = fotoImageService.create(fotoImageDTOConverter.convertDtoToEntity(fotoImage));
		em.flush();
		verify(publisher, times(0)).publish(any());
		FotoImage actual = fotoImageDTOConverter.convertEntityToDto(fotoImageEntity);
		
		
		assertThat(actual).isNotNull();
		assertThat(actual.getId()).isNotNull();
		assertThat(actual).isEqualToIgnoringGivenFields(fotoImage, IGNORED_FIELDS);
		
		assertThat(actual.getProduto()).isNull();
	}
	// END CREATE TESTS
	
	// BEGIN READ TESTS
	
	@Test
	public void testRead1() {
		FotoImageEntity expectedFotoImageEntity = newFotoImageEntity();
		java.util.UUID id = expectedFotoImageEntity.getId();
		FotoImage expected = fotoImageDTOConverter.convertEntityToDto(expectedFotoImageEntity);
		FotoImageEntity readFotoImageEntity = fotoImageService.read(id);
		FotoImage actual = fotoImageDTOConverter.convertEntityToDto(readFotoImageEntity);
		
		assertThat(actual).isEqualToComparingFieldByField(expected);
		
	}
	// END READ TESTS
	
	// BEGIN UPDATE TESTS
	
	@Test
	public void testUpdateWithAllFields() throws Exception {
		FotoImageEntity oldFotoImageEntity = newFotoImageEntity();
		java.util.UUID id = oldFotoImageEntity.getId();
				
		FotoImage fotoImage = new FotoImage();
		fotoImage.setId(id);
		
		fotoImage.setImagem("Unit tests".getBytes());
		fotoImage.setMiniatura("Unit tests".getBytes());
		fotoImage.setNome(generateRandomString(255));
		fotoImage.setDescricao(generateRandomString(255));
		fotoImage.setTamanho(-7132939175879393547L);
		fotoImage.setTipo(generateRandomString(255));
		
		ProdutoEntity produtoEntityParam = newProdutoEntity();
		ProdutoLookupResult produto = newProdutoLookupResult(produtoEntityParam);
		fotoImage.setProduto(produto);
		
		FotoImageEntity fotoImageEntity = fotoImageService.update(id, fotoImageDTOConverter.convertDtoToEntity(fotoImage));
		em.flush();
		verify(publisher, times(0)).publish(any());
		
		FotoImage actual = fotoImageDTOConverter.convertEntityToDto(fotoImageEntity);
		
		assertThat(actual).isNotNull();
		assertThat(actual.getId()).isNotNull();
		assertThat(actual).isEqualToIgnoringGivenFields(fotoImage, IGNORED_FIELDS);
		
		
		assertThat(actual.getProduto().getId()).isNotNull();
		assertThat(actual.getProduto()).isEqualToIgnoringGivenFields(fotoImage.getProduto(), IGNORED_FIELDS);
		
	}
	
	@Test
	public void testUpdateWithOnlyRecairedFields() throws Exception {
		FotoImageEntity oldFotoImageEntity = newFotoImageEntity();
		java.util.UUID id = oldFotoImageEntity.getId();
				
		FotoImage fotoImage = new FotoImage();
		fotoImage.setId(id);
		
		FotoImageEntity fotoImageEntity = fotoImageService.update(id, fotoImageDTOConverter.convertDtoToEntity(fotoImage));
		em.flush();
		verify(publisher, times(0)).publish(any());
		
		FotoImage actual = fotoImageDTOConverter.convertEntityToDto(fotoImageEntity);
		
		assertThat(actual).isNotNull();
		assertThat(actual.getId()).isNotNull();
		assertThat(actual).isEqualToIgnoringGivenFields(fotoImage, IGNORED_FIELDS);
		
		assertThat(actual.getProduto()).isNull();
	}
	// END UPDATE TESTS
	
	// BEGIN DELETE TESTS
	
	@Test
	public void testDelete1() {
		FotoImageEntity expected = newFotoImageEntity();
		java.util.UUID id = expected.getId();
		
		
		expected = em.find(FotoImageEntity.class, id);
		assertThat(expected).isNotNull();
		fotoImageService.delete(id);
		verify(publisher, times(0)).publish(any());
		
		expected = em.find(FotoImageEntity.class, id);
		assertThat(expected).isNull();
	}
	// END DELETE TESTS
	
	// BEGIN LIST TESTS
	// END LIST TESTS
	
	// BEGIN Autocomplete TESTS
	@Test
	public void testAutoComplete() {
		// Reset lastDate field to start LocalDate fields with today in this test. 
		resetNextDate();
					
		// Generate 33 records of data for FotoImageEntity for this test.
		List<FotoImageEntity> testData = new ArrayList<>();
		final int lastRecord = 33;
		final int firstRecord = 1;
		for (int i = firstRecord; i <= lastRecord; i++) {
			testData.add(newFotoImageEntity());
		}
		
		// Check if 33 records of FotoImageEntity was generated.
		long count = fotoImageRepository.count();
		assertThat(count).isEqualTo(lastRecord);
		
		// Extracts 1 records of FotoImageEntity randomly from testData.
		final int resultSize = 1;
		List<FotoImageEntity> filterTestData = getRandomItemsOf(testData, resultSize);
		
		// Extracts a list with only FotoImageEntity.nome field and configure this list as a filter.
		List<String> nomeListFilter = filterTestData.stream().map(FotoImageEntity::getNome).collect(Collectors.toList());
		// Mount the autocomplete query expression and call it.
		String query = nomeListFilter.get(0);
		Collection<FotoImageAutoComplete> result = fotoImageService.autoComplete(query);
		
		// Assert FotoImageAutoComplete results.
		assertThat(result).isNotNull().hasSize(1)
		.extracting(FotoImageAutoComplete::getNome)
		.containsExactlyInAnyOrderElementsOf(nomeListFilter);
	}
	
	// END Autocomplete TESTS
	
	
	// BEGIN Relationships Autocomplete TESTS
	
	@Test
	public void testFotoImageProdutoAutoComplete() {
		// Reset lastDate field to start LocalDate fields with today in this test. 
		resetNextDate();
					
		// Generate 3 records of data for ProdutoEntity for this test.
		List<ProdutoEntity> testData = new ArrayList<>();
		final int lastRecord = 3;
		final int firstRecord = 1;
		for (int i = firstRecord; i <= lastRecord; i++) {
			testData.add(newProdutoEntity());
		}
		
		// Check if 3 records of ProdutoEntity was generated.
		long count = produtoRepository.count();
		assertThat(count).isEqualTo(lastRecord);
		
		// Extracts 1 records of ProdutoEntity randomly from testData.
		final int resultSize = 1;
		List<ProdutoEntity> filterTestData = getRandomItemsOf(testData, resultSize);
		
		// Extracts a list with only ProdutoEntity.nome field and configure this list as a filter.
		List<String> nomeListFilter = filterTestData.stream().map(ProdutoEntity::getNome).collect(Collectors.toList());
		String query = nomeListFilter.get(0);
		
		Collection<ProdutoAutoComplete> result = fotoImageService.produtoProdutoAutoComplete(query);
		
		assertThat(result).isNotNull().hasSize(1)
		.extracting(ProdutoAutoComplete::getNome)
		.containsExactlyInAnyOrderElementsOf(nomeListFilter);
	}
	
	// END Relationships Autocomplete TESTS
	
	// BEGIN tests for Sum Fields
	// END tests for Sum Fields
	
	// BEGIN tests for Sum Fields
	// END tests for Sum Fields
	
	// BEGIN TESTS DEPENDENCIES
	
	
	protected FotoImageEntity newFotoImageEntity() {
		FotoImageEntity fotoImageEntity = new FotoImageEntity();
		
		fotoImageEntity.setImagem("Unit tests".getBytes());
		fotoImageEntity.setMiniatura("Unit tests".getBytes());
		fotoImageEntity.setNome(generateRandomString(255));
		fotoImageEntity.setDescricao(generateRandomString(255));
		fotoImageEntity.setTamanho(-6667533241901063198L);
		fotoImageEntity.setTipo(generateRandomString(255));
		fotoImageEntity.setProduto(newProdutoEntity());
		
		fotoImageEntity = em.persistAndFlush(fotoImageEntity);
		return fotoImageEntity;
	}
	
	
	protected FotoImageLookupResult newFotoImageLookupResult(FotoImageEntity fotoImageEntity) {
		FotoImageLookupResult fotoImage = new FotoImageLookupResult();
		
		fotoImage.setId(fotoImageEntity.getId());
		fotoImage.setNome(fotoImageEntity.getNome());
		
		return fotoImage;
	}
	
	
	protected ProdutoEntity newProdutoEntity() {
		ProdutoEntity produtoEntity = new ProdutoEntity();
		
		produtoEntity.setNome(generateRandomString(255));
		
		produtoEntity.setFotos(newFotoEntityList(3, produtoEntity));
		produtoEntity = em.persistAndFlush(produtoEntity);
		return produtoEntity;
	}
	
	
	protected ProdutoLookupResult newProdutoLookupResult(ProdutoEntity produtoEntity) {
		ProdutoLookupResult produto = new ProdutoLookupResult();
		
		produto.setId(produtoEntity.getId());
		produto.setNome(produtoEntity.getNome());
		
		return produto;
	}
	
	protected Set<FotoEntity> newFotoEntityList(int listSize, ProdutoEntity produto) {
		Set<FotoEntity> result = new HashSet<>(listSize);
		while (result.size() < listSize) {
			result.add(newFotoEntity(produto));
		}
		return result;
	}
	
	
	protected FotoEntity newFotoEntity(ProdutoEntity produto) {
		FotoEntity fotoEntity = new FotoEntity();
		
		fotoEntity.setNome(generateRandomString(255));
		fotoEntity.setDescricao(generateRandomString(255));
		fotoEntity.setTamanho(394252977634172190L);
		fotoEntity.setTipo(generateRandomString(255));
		fotoEntity.setProduto(produto);
		
		return fotoEntity;
	}
	
	
	protected FotoLookupResult newFotoLookupResult(FotoEntity fotoEntity) {
		FotoLookupResult foto = new FotoLookupResult();
		
		foto.setId(fotoEntity.getId());
		foto.setNome(fotoEntity.getNome());
		
		return foto;
	}
	// END TESTS DEPENDENCIES

}
