/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.entity.foto;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.validation.constraints.NotBlank;
import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoLookupResult;

public class Foto {

	private java.util.UUID id;
	
	@NotNull(message="\"imagem\" é obrigatório.")
	private byte[] imagem;
	
	private byte[] miniatura;
	
	@Size(max = 255, message = "\"nome\" pode ter no máximo 255 caracteres.")
	private String nome;
	
	@Size(max = 255, message = "\"descricao\" pode ter no máximo 255 caracteres.")
	private String descricao;
	
	private Long tamanho;
	
	@NotBlank(message="\"tipo\" é obrigatório.")
	@Size(max = 255, message = "\"tipo\" pode ter no máximo 255 caracteres.")
	private String tipo;
	
	@NotNull(message="\"Produto\" é obrigatório.")
	private ProdutoLookupResult produto;
	
	
	public Foto() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}
	
	
	public java.util.UUID getId() {
		return id;
	}
	
	public byte[] getImagem() {
		return imagem;
	}
	
	public byte[] getMiniatura() {
		return miniatura;
	}
	
	public String getNome() {
		return nome;
	}
	
	public String getDescricao() {
		return descricao;
	}
	
	public Long getTamanho() {
		return tamanho;
	}
	
	public String getTipo() {
		return tipo;
	}
	
	public ProdutoLookupResult getProduto() {
		return produto;
	}
	
	public void setId(java.util.UUID id) {
		this.id = id;
	}
	
	public void setImagem(byte[] imagem) {
		this.imagem = imagem;
	}
	
	public void setMiniatura(byte[] miniatura) {
		this.miniatura = miniatura;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	public void setTamanho(Long tamanho) {
		this.tamanho = tamanho;
	}
	
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
	public void setProduto(ProdutoLookupResult produto) {
		this.produto = produto;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Foto other = (Foto) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		
		return true;
	}
	
	@Override
	public int hashCode() {
		return 31;
	}
	
	/* 
	@Override
	public String toString() {
		// Enabling toString for JPA entities will implicitly trigger lazy loading on all fields.
	}
	*/

}
