/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.entity.foto;



public interface FotoAutoComplete {

	java.util.UUID getId();
	
	String getNome();
	
	void setId(java.util.UUID id);
	
	void setNome(String nome);

}
