/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


package br.com.kerubin.api.cadastros.fornecedor.entity.foto;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import br.com.kerubin.api.servicecore.mapper.ObjectMapper;

@Component
public class FotoDTOConverter {

	@Inject
	private ObjectMapper mapper;

	public Foto convertEntityToDto(FotoEntity entity) {
		Foto dto = null;
		if (entity != null) {
			dto = mapper.map(entity, Foto.class, true); // Do not permit passwords fields go outside.
		}
		return dto;
	}


	public FotoEntity convertDtoToEntity(Foto dto) {
		FotoEntity entity = null;
		if (dto != null) {
			entity = mapper.map(dto, FotoEntity.class);
		}
		return entity;
	}


}