/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.entity.foto;

import java.util.stream.Collectors;

import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.DeleteMapping;

import br.com.kerubin.api.cadastros.fornecedor.common.PageResult;

		
import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoAutoComplete;

import java.util.Collection;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.RequestParam;

@RestController
@RequestMapping("cadastros/fornecedor/entities/foto")
public class FotoController {
	
	@Autowired
	private FotoService fotoService;
	
	@Autowired
	FotoDTOConverter fotoDTOConverter;
	
	@Transactional
	@PostMapping
	public ResponseEntity<Foto> create(@Valid @RequestBody Foto foto) {
		FotoEntity fotoEntity = fotoService.create(fotoDTOConverter.convertDtoToEntity(foto));
		return ResponseEntity.status(HttpStatus.CREATED).body(fotoDTOConverter.convertEntityToDto(fotoEntity));
	}
	
	@Transactional(readOnly = true)
	@GetMapping("/{id}")
	public ResponseEntity<Foto> read(@PathVariable java.util.UUID id) {
		try {
			FotoEntity fotoEntity = fotoService.read(id);
			return ResponseEntity.ok(fotoDTOConverter.convertEntityToDto(fotoEntity));
		}
		catch(IllegalArgumentException e) {
			return ResponseEntity.notFound().build();
		}
	}
	
	@Transactional
	@PutMapping("/{id}")
	public ResponseEntity<Foto> update(@PathVariable java.util.UUID id, @Valid @RequestBody Foto foto) {
		try {
			FotoEntity fotoEntity = fotoService.update(id, fotoDTOConverter.convertDtoToEntity(foto));
			return ResponseEntity.ok(fotoDTOConverter.convertEntityToDto(fotoEntity));
		}
		catch(IllegalArgumentException e) {
			return ResponseEntity.notFound().build();
		}
	}
	
	@ResponseStatus(HttpStatus.NO_CONTENT)
	@DeleteMapping("/{id}")
	public void delete(@PathVariable java.util.UUID id) {
		fotoService.delete(id);
	}
	
	@ResponseStatus(HttpStatus.NO_CONTENT)
	@PostMapping("/deleteInBulk")
	public void deleteInBulk(@RequestBody java.util.List<java.util.UUID> idList) {
		fotoService.deleteInBulk(idList);
	}
	
	@Transactional(readOnly = true)
	@GetMapping
	public PageResult<Foto> list(FotoListFilter fotoListFilter, Pageable pageable) {
		Page<FotoEntity> page = fotoService.list(fotoListFilter, pageable);
		List<Foto> content = page.getContent().stream().map(pe -> fotoDTOConverter.convertEntityToDto(pe)).collect(Collectors.toList());
		PageResult<Foto> pageResult = new PageResult<>(content, page.getNumber(), page.getSize(), page.getTotalElements());
		return pageResult;
	}
	
	@Transactional(readOnly = true)
	@GetMapping("/autoComplete")
	public Collection<FotoAutoComplete> autoComplete(@RequestParam("query") String query) {
		Collection<FotoAutoComplete> result = fotoService.autoComplete(query);
		return result;
	}
	
	
	
	// Begin relationships autoComplete 
	
	@Transactional(readOnly = true)
	@GetMapping("/produtoProdutoAutoComplete")
	public Collection<ProdutoAutoComplete> produtoProdutoAutoComplete(@RequestParam("query") String query) {
		Collection<ProdutoAutoComplete> result = fotoService.produtoProdutoAutoComplete(query);
		return result;
	}
	
	// End relationships autoComplete
	
}
