/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.entity.foto;

import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoAutoComplete;

public interface FotoService {
	
	public FotoEntity create(FotoEntity fotoEntity);
	
	public FotoEntity read(java.util.UUID id);
	
	public FotoEntity update(java.util.UUID id, FotoEntity fotoEntity);
	
	public void delete(java.util.UUID id);
	
	public void deleteInBulk(java.util.List<java.util.UUID> idList);
	
	public Page<FotoEntity> list(FotoListFilter fotoListFilter, Pageable pageable);
	
	public Collection<FotoAutoComplete> autoComplete(String query);
	
	// Begin relationships autoComplete 
	public Collection<ProdutoAutoComplete> produtoProdutoAutoComplete(String query);
	// End relationships autoComplete
	 
}
