/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.fornecedor.foto;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import br.com.kerubin.api.cadastros.fornecedor.entity.produto.ProdutoLookupResult;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class FotoDTO {

	private java.util.UUID id;
	
	@NotNull(message="\"imagem\" é obrigatório.")
	private String imagem;
	
	private String miniatura;
	
	@Size(max = 255, message = "\"nome\" pode ter no máximo 255 caracteres.")
	private String nome;
	
	@Size(max = 255, message = "\"descricao\" pode ter no máximo 255 caracteres.")
	private String descricao;
	
	private Long tamanho;
	
	@NotBlank(message="\"tipo\" é obrigatório.")
	@Size(max = 255, message = "\"tipo\" pode ter no máximo 255 caracteres.")
	private String tipo;
	
	@NotNull(message="\"Produto\" é obrigatório.")
	private ProdutoLookupResult produto;
	
}
